// <auto-generated />
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250607165200_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pais_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 4,
                            Name = "Roma"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BR",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "FR",
                            CountryName = "França"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CA",
                            CountryName = "Canadá"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "IT",
                            CountryName = "Itália"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT")
                        .HasColumnName("preco_diaria");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Apartamento Copacabana",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Flat na Champs-Élysées",
                            PricePerNight = 550.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Condo no centro de Toronto",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Hotel perto do Coliseu",
                            PricePerNight = 450.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
