// <auto-generated />
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250607170719_SeedMoreInitialData")]
    partial class SeedMoreInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pais_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Salvador"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Nice"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "Montreal"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 4,
                            Name = "Roma"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 4,
                            Name = "Milão"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            Name = "Veneza"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BR",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "FR",
                            CountryName = "França"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CA",
                            CountryName = "Canadá"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "IT",
                            CountryName = "Itália"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT")
                        .HasColumnName("preco_diaria");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Apartamento Copacabana",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Casa em Ipanema",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Studio em Botafogo",
                            PricePerNight = 250.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Flat na Av. Paulista",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Apartamento Jardins",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Name = "Loft Vila Madalena",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Name = "Apartamento Pelourinho",
                            PricePerNight = 200.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            Name = "Casa Praia do Forte",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Name = "Pousada Barra",
                            PricePerNight = 250.00m
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            Name = "Flat na Champs-Élysées",
                            PricePerNight = 550.00m
                        },
                        new
                        {
                            Id = 11,
                            CityId = 4,
                            Name = "Apartamento Montmartre",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 12,
                            CityId = 4,
                            Name = "Studio Torre Eiffel",
                            PricePerNight = 600.00m
                        },
                        new
                        {
                            Id = 13,
                            CityId = 5,
                            Name = "Apartamento Presqu'île",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 14,
                            CityId = 5,
                            Name = "Loft Croix-Rousse",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 15,
                            CityId = 5,
                            Name = "Studio Vieux Lyon",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 16,
                            CityId = 6,
                            Name = "Apartamento Promenade des Anglais",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 17,
                            CityId = 6,
                            Name = "Villa Côte d'Azur",
                            PricePerNight = 1000.00m
                        },
                        new
                        {
                            Id = 18,
                            CityId = 6,
                            Name = "Studio Centro Histórico",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 19,
                            CityId = 7,
                            Name = "Condo no centro de Toronto",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 20,
                            CityId = 7,
                            Name = "Apartamento Distillery District",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 21,
                            CityId = 7,
                            Name = "Loft Queen Street",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 22,
                            CityId = 8,
                            Name = "Apartamento Coal Harbour",
                            PricePerNight = 600.00m
                        },
                        new
                        {
                            Id = 23,
                            CityId = 8,
                            Name = "Casa Kitsilano",
                            PricePerNight = 700.00m
                        },
                        new
                        {
                            Id = 24,
                            CityId = 8,
                            Name = "Studio Gastown",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 25,
                            CityId = 9,
                            Name = "Apartamento Vieux-Montréal",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 26,
                            CityId = 9,
                            Name = "Loft Plateau Mont-Royal",
                            PricePerNight = 350.00m
                        },
                        new
                        {
                            Id = 27,
                            CityId = 9,
                            Name = "Studio Quartier Latin",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 28,
                            CityId = 10,
                            Name = "Hotel perto do Coliseu",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 29,
                            CityId = 10,
                            Name = "Apartamento Trastevere",
                            PricePerNight = 400.00m
                        },
                        new
                        {
                            Id = 30,
                            CityId = 10,
                            Name = "Studio Fontana di Trevi",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 31,
                            CityId = 11,
                            Name = "Apartamento Quadrilátero da Moda",
                            PricePerNight = 600.00m
                        },
                        new
                        {
                            Id = 32,
                            CityId = 11,
                            Name = "Loft Navigli",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 33,
                            CityId = 11,
                            Name = "Studio Duomo",
                            PricePerNight = 550.00m
                        },
                        new
                        {
                            Id = 34,
                            CityId = 12,
                            Name = "Apartamento perto da Praça de São Marcos",
                            PricePerNight = 500.00m
                        },
                        new
                        {
                            Id = 35,
                            CityId = 12,
                            Name = "Casa Canal Grande",
                            PricePerNight = 800.00m
                        },
                        new
                        {
                            Id = 36,
                            CityId = 12,
                            Name = "Studio Rialto",
                            PricePerNight = 450.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
